### ISSUE TITLE
Fork and relicensed version of node-red-contrib-minio-all?

### ISSUE THREAD

**Issue by ViViDboarder** [alpine-code/node-red-contrib-minio#1]
Hello. I was looking for a Minio node and found both this and https://github.com/InferSens/node-red-contrib-minio-all.

The initial commit of this repo appears to be nearly identical (including comments) to the code by @colin-infersens, but with an MIT license instead of Apache.

Is there anything added from this fork?

**Comment by ilzenzo** [comment]
Hello!

Yes indeed, there are minimal but substantial changes to deal this particular issue: https://github.com/InferSens/node-red-contrib-minio-all/issues/5.

As it fundamentally change the output behaviour of most nodes, I concluded it was more reasonable to setup a new project.

**Comment by ilzenzo** [comment]
Hello!
Tha

**Comment by ilzenzo** [comment]
Hello!

There is indeed minimal but substantial rework to preserve the msg payload across nodes. 
Such change fundamentally change the output behaviour of nodes. Due to this reason, a new project has been created. 

I hope this answers.
